### ISSUE TITLE
Avoiding "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by timoxley** [dominictarr/pull-stream#14]
e.g.

```js
var pull = require('pull-stream')
var toPull = require('stream-to-pull-stream')

pull(
    pull.infinite(),
    pull.map(function(data) {return String(data)}),
    toPull(process.stdout)
)
```

Produces a bunch of output before erroring with `RangeError: Maximum call stack size exceeded`. I understand why, but perhaps something could trampoline or occasionally push an operation to the next tick. Another module do you think?

**Comment by anko** [comment]
_Updaaaate_: ES2015 mandates proper tail call optimisation, so @timoxley's [original example](https://github.com/dominictarr/pull-stream/issues/14#issue-17435335) now runs without blowing the stack in Node v5.10.1, and a trivial [browserified](http://browserify.org/) modification does the same in Chromium 49.0.2623.110.

:balloon:

**Comment by dominictarr** [comment]
@anko did you run the latest deps or the old deps? I'm pretty i fixed this some time back then (but didn't close the issue obviously)

**Comment by anko** [comment]
@dominictarr Latest. I assumed this would have been closed if the problem had been fixed in code. Apparently, it [has been](https://github.com/dominictarr/pull-stream/blob/master/sinks.js#L22-L24). Oops.

**Comment by dominictarr** [comment]
yup, although this particular problem was fixed like this https://github.com/dominictarr/stream-to-pull-stream/blob/master/index.js#L45-L71

I think I tried to use https://www.npmjs.com/package/looper but there was a bug somewhere and couldn't figure out why and so just went to nextTick which is less performant but still correct
