### ISSUE TITLE
through question

### ISSUE THREAD

**Issue by dweinstein** [dominictarr/pull-stream#23]
With https://github.com/rvagg/through2#transformfunction I'd do something like `this.push(...)` to queue up multiple objects to send down the stream with a subsequent `cb(...)`. This doesn't seem possible with `pull.Through` or am I missing something?

**Comment by dweinstein** [comment]
hrm well I tried it out and I decided to do what felt like a dirty thing and call the `cb` multiple times... is this what you'd suggest?

**Comment by dominictarr** [comment]
no do not call the cb multiple times. I wrote all my pull streams assuming you do not do that, so i'd expect something _very hard to debug_ will happen sooner or later.

instead what you want is https://github.com/dominictarr/pull-through it gives you the familiar `through` interface to pull streams.

Another way you can do it is by combining `pull.map` with `pull.flatten`:

``` js
function createFooBarBazSplitter () {
  return pull(
    pull.map(function (data) {
      return [data.foo, data.bar, data.baz]
    }),
    pull.flatten()
  )
}
```
flatten will take a stream of arrays and turn it into one stream of the array items.

**Comment by dominictarr** [comment]
note, this does have a small difference, for each incoming chunk that becomes multilpe chunks you have to decide what they will be all at once.

**Comment by dweinstein** [comment]
pull-through looked interesting but having trouble seeing how to use it async, there's no cb like through2?

I'll try your map/flatten example with `.asyncMap`

**Comment by dweinstein** [comment]
actually I guess I can split my pipeline between an async piece that handles that and keep the through part that splits stuff off as a separate piece ...

**Comment by dweinstein** [comment]
actually probably I can use `pull-through` but tweak the ender

**Comment by dominictarr** [comment]
yeah, pull-through is like the original through, which didn't have the cb. If you are still having trouble explain what you are trying to do and post your code.

**Comment by dweinstein** [comment]
I think I'm all set, thanks!
