### ISSUE TITLE
pull.take(n) calls upstream.read(null, cb) n+1 times

### ISSUE THREAD

**Issue by regular** [dominictarr/pull-stream#25]
Example code:

``` js
var pull = require('pull-stream');

function source() {
    var i = 0;
    return function read(abort, cb) {
        console.log('READ, abort:', abort);
        cb(null, i++);
    }; 
}

pull(
    source(),
    pull.take(2),
    pull.log()
);
```

output:

```
READ, abort: null
0
READ, abort: null
1
READ, abort: null
READ, abort: true
```

I understand that the additional `read()` is necessary in case `take` is passed a function, because then the stop condition may depend on the new data. However, when you pass in a number, the additional `read` comes as a surprise.

In my case it causes an http request to fill a buffer that will never be used.

**Comment by dominictarr** [comment]
correct. I made a version of take that uses a number and only reads that exact number of times... but didn't publish it as it's own module. prehaps this could be worked into pull.take some how?

https://github.com/dominictarr/pull-level/blob/master/test/helper/index.js#L77-L87

maybe the test function should just return wether to continue, and there would be an option to also return the last selected item... that would probably be simpler than having the function return a boolean, _and_ wether to read more. Then, using a number as `fn` could set that as the default mode.

**Comment by regular** [comment]
Then `test` would also be more similar to `drain`'s callback, right? (returning false when you don't want to continue)

That would be a breaking API change though. If you don't have a problem with that, I could work on a PR.

**Comment by dominictarr** [comment]
Sure! After thinking about it, my bet is that a `last: boolean` config
option will produce nicer code. PR would be great!
