### ISSUE TITLE
docs: clarify what happens to the data when a read function calls cb(true, data)

### ISSUE THREAD

**Issue by regular** [dominictarr/pull-stream#26]
From the docs I couldn't tell (maybe it slipped my attention) whether it is okay to call the callback with err===true _and_ providing a last chunk of data.

What will happen of course depends on the reader implementation. I think there should be a very clear rule about this.

**Comment by dominictarr** [comment]
Nope. There should be no data. All the pull modules I wrote would drop that.

**Comment by regular** [comment]
#27 should remove any doubt a reader might have.

**Comment by regular** [comment]
I am confused by [this line](https://github.com/dominictarr/pull-stream/blob/master/throughs.js#L149).
When explicitly called with `true` as the first argument, a read function will always call its callback with err===true, right? So it never will provide data when called with true as the fir argument, right?

Shouldn't it simply be:

       read(true, function () {
           cb(true)
         })

Am I missing something?

**Comment by dominictarr** [comment]
yeah, that would be better.
Maybe sometimes there is an error you need to know about so it should be `cb(err)` or `cb(err||true)` to ensure it's a end value.

**Comment by regular** [comment]
Yes, but In that particular case the function early-returns when `err` is trueish, so that's safe, I think.

**Comment by dominictarr** [comment]
yeah, but if an error occured, you want to pass that to the user so they have the chance to react, if necessary.

**Comment by regular** [comment]
ah, now I see what you mean,.
I was confused, because the original code did not pass the `err` down either :)

I think it should be:

```
read(null, function (end, data) {
      if(ended = ended || end) return cb(ended)
      if(!test(data)) {
        ended = true
        read(true, function (err) {
          last ? cb(err, data) : cb(err || true)
        })
      }
      else
        cb(null, data)
    })
```
I'll try and write a test for the error case.

**Comment by dominictarr** [comment]
Hmm, but shouldn't `cb(err, data)` if the abort fails...

Maybe instead of aborting immediately after the test fails...
it might be better to abort on the next request, which would `cb(true)`.

**Comment by regular** [comment]
Not sure I get what you are saying. If the test fails and we don't want the last item, we have to `cb(true)` and then there won't be a next request, right?

Maybe like this?

    last ? cb(err, err ? undefined : data) : cb(err || true)

**Comment by dominictarr** [comment]
if the `!test(data) && !last` then we must abort the stream,
but if `!test(data) && last` then we should abort the stream on the next request.

I am preparing a pull request.

**Comment by regular** [comment]
yes, that makes sense. ...
