### ISSUE TITLE
where did group go?

### ISSUE THREAD

**Issue by dweinstein** [dominictarr/pull-stream#38]

**Comment by dominictarr** [comment]
oh, sorry, for version 3 I removed a trimmed down core pull-stream, removing stuff that i didn't seem to use.
I have just republished it as `pull-group` for you.

**Comment by dweinstein** [comment]
sweet thanks I'll give it a try. keep up the amazing work and thanks for the quick reply.

**Comment by dominictarr** [comment]
no problem!
